import type { GameSource } from '../schema/source.ts';

// This registry is internal evidence metadata. Its URLs are never rendered publicly.
export const gameSources: GameSource[] = [
  {
    id: 'official-roblox-game-2026-09-09',
    title: 'Karinderya Roblox game page',
    sourceTier: 'OFFICIAL_GAME',
    url: 'https://www.roblox.com/games/116497287371701/Karinderya',
    accessedAt: '2026-09-09',
    notes: 'Creator-owned game listing; useful for identity and broad game positioning only.',
  },
  {
    id: 'gameplay-placement-capture-2026-08-29',
    title: 'Dated Karinderya placement interface capture',
    sourceTier: 'DIRECT_GAMEPLAY',
    url: 'https://earnaldo.com/blog/karinderya-beginner-guide',
    accessedAt: '2026-09-09',
    notes: 'Shows readable stove names. It does not verify performance, cost, capacity, or current availability.',
  },
  {
    id: 'gameplay-grocery-capture-2026-09-02',
    title: 'Dated Karinderya Grocery interface capture',
    sourceTier: 'DIRECT_GAMEPLAY',
    url: 'https://karinderya.org/wiki/ingredients/',
    accessedAt: '2026-09-09',
    notes: 'Shows readable Rice and Condiments listings. It does not verify prices, quantities, recipes, or current availability.',
  },
  {
    id: 'community-furniture-names-2026-09-02',
    title: 'Community furniture-name inventory',
    sourceTier: 'SECONDARY',
    url: 'https://karinderyawiki.com/guides/furniture-guide',
    accessedAt: '2026-09-09',
    notes: 'Discovery-only evidence for table names; requires creator-owned or direct current-game confirmation.',
  },
  {
    id: 'community-chiller-report-2026-08-29',
    title: 'Community Worker and Chiller event report',
    sourceTier: 'SECONDARY',
    url: 'https://karinderyagame.wiki/updates/worker-chiller/',
    accessedAt: '2026-09-09',
    notes: 'Discovery-only evidence. It does not establish Chiller function, acquisition, cost, or current availability.',
  },
  {
    id: 'community-menu-capture-report-2026-08-30',
    title: 'Community report of dated Karinderya menu captures',
    sourceTier: 'SECONDARY',
    url: 'https://karinderiacodex.com/recipes/menu-and-unlocks/',
    accessedAt: '2026-09-09',
    notes: 'Discovery lead for menu names and unlock evidence. Original frames must be reviewed before creating dish or recipe entities.',
  },
  {
    id: 'serp-database-competitor-2026-09-09',
    title: 'Karinderya database and calculator competitor snapshot',
    sourceTier: 'UNVERIFIED',
    url: 'https://karinderya.pro/',
    accessedAt: '2026-09-09',
    notes: 'Search-intent and competitor-format evidence only. Its game values and formulas are not imported.',
  },
  {
    id: 'gameplay-challs-2026-08-22',
    title: 'Karinderya Guide! (Tips & Tricks) ROBLOX — CHALLS',
    sourceTier: 'DIRECT_GAMEPLAY',
    url: 'https://www.youtube.com/watch?v=oPA7wdbRvb0',
    accessedAt: '2026-09-09',
    notes: 'Dated gameplay lead with reported Shop and stove timestamps. Frames could not be directly reviewed in this environment, so no field is upgraded from this source yet.',
  },
  {
    id: 'gameplay-berlian-2026-08-20',
    title: '2 NEW CODES & HOW TO PLAY KARINDERYA! — Berlian kecil',
    sourceTier: 'DIRECT_GAMEPLAY',
    url: 'https://www.youtube.com/watch?v=C1UrKqbemlM',
    accessedAt: '2026-09-09',
    notes: 'Dated tutorial and service-flow lead. Video fetch was throttled, so visible UI text was not promoted into structured fields.',
  },
  {
    id: 'public-gameplay-grocery-ui-2026-08-24',
    title: 'Karinderya Grocery UI capture',
    sourceTier: 'DIRECT_GAMEPLAY',
    url: 'https://karinderyawiki.com/images/articles/karinderya-grocery-categories.webp',
    accessedAt: '2026-09-10',
    versionScope: 'observed-2026-08-24',
    notes: 'Tier 2 public gameplay screenshot. The Grocery heading, category tabs, 25kg Rice, Condiments, and their displayed Cash values are readable. Values remain dated observations, not current-version guarantees.',
  },
  {
    id: 'public-gameplay-furniture-effects-ui-2026-09-02',
    title: 'Karinderya furniture and stove upgrade dialogue capture',
    sourceTier: 'DIRECT_GAMEPLAY',
    url: 'https://karinderyawiki.com/images/articles/karinderya-furniture-upgrade-effects.webp',
    accessedAt: '2026-09-10',
    versionScope: 'observed-2026-09-02',
    notes: 'Tier 2 public gameplay screenshot with readable qualitative shopkeeper dialogue. It supports only category-level discovery because no specific table, chair, or stove entity is selected in the frame.',
  },
  {
    id: 'public-gameplay-menu-ui-2026-08-24',
    title: 'Karinderya Menu unlock UI capture',
    sourceTier: 'DIRECT_GAMEPLAY',
    url: 'https://karinderyawiki.com/images/articles/karinderya-menu-unlocks.webp',
    accessedAt: '2026-09-10',
    versionScope: 'observed-2026-08-24',
    notes: 'Tier 2 public gameplay screenshot. MENU, LUGAW, Plain and Goto, SILOG MEALS, and the visible unlock progress are readable. No ingredient requirement is visible, so it cannot support a recipe entity or relationship.',
  },
  {
    id: 'public-gameplay-furniture-shop-ui-2026-09-02',
    title: 'Karinderya Furniture Shop table capture',
    sourceTier: 'DIRECT_GAMEPLAY',
    url: 'https://karinderyawiki.com/images/articles/karinderya-furniture-prices-v2.webp',
    accessedAt: '2026-09-10',
    versionScope: 'observed-2026-09-02',
    notes: 'Tier 2 public gameplay screenshot. The Furniture Shop table category and a red wooden table entry are visually clear. Translated UI labels and dated values are not treated as permanent names or prices.',
  },
];

export const gameSourceById = new Map(gameSources.map((source) => [source.id, source]));
